/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "log-viewer.hosts": [],
    "log-viewer.folders": [],
    "log-viewer.folders.request-download": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.folders.clear-cache": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.folders.delete": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.files": [],
    "log-viewer.files.request-download": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.clear-cache": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.delete": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.clear-cache-all": [],
    "log-viewer.files.delete-multiple-files": [],
    "log-viewer.logs": [],
    "log-viewer.folders.download": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.download": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.index": [
        {
            "name": "view",
            "required": false
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "designs": [],
    "designs.create": [],
    "designs.store": [],
    "designs.show": [
        {
            "name": "design",
            "required": true,
            "binding": "id"
        }
    ],
    "designs.edit": [
        {
            "name": "design",
            "required": true
        }
    ],
    "designs.update": [
        {
            "name": "design",
            "required": true
        }
    ],
    "designs.destroy": [
        {
            "name": "design",
            "required": true
        }
    ],
    "mockups.create": [],
    "mockups.editor": [],
    "mockups.show": [
        {
            "name": "mockup",
            "required": true,
            "binding": "id"
        }
    ],
    "mockups": [],
    "mockups.save": [],
    "mockups.update": [
        {
            "name": "mockup",
            "required": true,
            "binding": "id"
        }
    ],
    "mockup-templates": [],
    "mockup-templates.create": [],
    "mockup-templates.store": [],
    "mockup-templates.show": [
        {
            "name": "template",
            "required": true,
            "binding": "id"
        }
    ],
    "mockup-templates.editor": [
        {
            "name": "template",
            "required": true,
            "binding": "id"
        }
    ],
    "mockup-templates.update": [
        {
            "name": "template",
            "required": true,
            "binding": "id"
        }
    ],
    "mockup-templates.destroy": [
        {
            "name": "template",
            "required": true,
            "binding": "id"
        }
    ],
    "products.index": [],
    "products.create": [],
    "products.store": [],
    "products.show": [
        {
            "name": "product",
            "required": true
        }
    ],
    "products.edit": [
        {
            "name": "product",
            "required": true
        }
    ],
    "products.update": [
        {
            "name": "product",
            "required": true
        }
    ],
    "products.destroy": [
        {
            "name": "product",
            "required": true
        }
    ],
    "user.landing": [],
    "user.dashboard": [],
    "user.profile.edit": [],
    "user.profile.update": [],
    "user.profile.destroy": [],
    "user.register": [],
    "user.": [],
    "user.login": [],
    "user.password.request": [],
    "user.password.email": [],
    "user.password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "user.password.store": [],
    "user.verification.notice": [],
    "user.verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "user.verification.send": [],
    "user.password.confirm": [],
    "user.password.update": [],
    "user.logout": [],
    "landing": [],
    "dashboard": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
