/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "user.landing": [],
    "user.dashboard": [],
    "user.profile.edit": [],
    "user.profile.update": [],
    "user.profile.destroy": [],
    "user.register": [],
    "user.": [],
    "user.login": [],
    "user.password.request": [],
    "user.password.email": [],
    "user.password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "user.password.store": [],
    "user.verification.notice": [],
    "user.verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "user.verification.send": [],
    "user.password.confirm": [],
    "user.password.update": [],
    "user.logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
