<?php

namespace App\Traits;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;

trait HasSlug
{
    public static function bootHasSlug(): void
    {
        static::creating(function (Model $model) {
            $slugField = $model->slugField ?? 'title';

            $title = ($model->addTimestampsToSlug ?? false) ? $model->{$slugField}.'-'.now()->timestamp : $model->{$slugField};

            $model->slug = $model->generateSlug($title);
        });
    }

    /**
     * Generate a unique slug from the given title.
     *
    * It starts with the base slug generated by Str::slug().
    * If a record with that slug exists, it appends an incrementing suffix.
    *
    * @param string $title
    * @return string
    */
   protected function generateSlug(string $title): string
   {
       $baseSlug = Str::slug($title);
       $slug = $baseSlug;
       $i = 1;

       // Loop until a unique slug is found.
       while (static::where('slug', $slug)->exists()) {
           $slug = $baseSlug . '-' . $i;
           $i++;
       }

       return $slug;
   }
}
